name: duble_gem
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  file_picker: ^10.3.3
  flutter_localizations:
    sdk: flutter

# fonts: put any Persian font files under assets/fonts/ and reference below
flutter:
  uses-material-design: true
  assets:
    - assets/sample.txt
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Regular.ttf
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
